- name: Execute output
  become: yes
  hosts: be
  gather_facts: False
  vars:
    sum: 0
  tasks:
    - name: Read values from files and sum them up
      shell: cat /var/log/mailstat_r-{{ even_date }} #| awk '{sum += $1} END {print sum}'
      register: sum
      loop: [20240603, 20240604, 20240605, 20240606, 20240607, 20240608, 20240609]
      loop_control:
        loop_var: even_date
      when: even_date > 6

    - set_fact:   # Складываем содержимое файла с предыдущим выводом.
        sum_stdout: "{{ (sum_stdout | default(0) | int) + (sum.results[item].stdout | int) }}"
      loop: [0, 1, 2, 3, 4, 5, 6]

- name: Output
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Write results to local output file  # Записываем все в файл на локальной машине
      copy:
        dest: "/home/aayurlov/sum.txt"
        content: |
          {% for host in groups.be %}
          === {{ host }} ==

          {{hostvars[host].sum_stdout}}

          {% endfor %}
