---

- name: Install and configure Node Exporter on servers
  hosts: all
  become: true

  tasks:
    - name: Download NodeExporter archive
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-1.0.1.linux-amd64.tar.gz"

    - name: Extract NodeExporter archive
      ansible.builtin.command: "tar zxvf /tmp/node_exporter-1.0.1.linux-amd64.tar.gz"
      args:
        chdir: "/tmp"

    - name: Copy NodeExporter executable to /usr/local/bin/
      ansible.builtin.command: "cp /tmp/node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/"

    - name: Create user nodeusr
      ansible.builtin.user:
        name: "nodeusr"
        shell: "/bin/false"
        system: yes

    - name: Change ownership of NodeExporter executable
      ansible.builtin.file:
        path: "/usr/local/bin/node_exporter"
        owner: "nodeusr"
        group: "nodeusr"

    - name: Create systemd unit file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=NodeExporter

          [Service]
          TimeoutStartSec=0
          User=nodeusr
          ExecStart=/usr/local/bin/node_exporter --web.listen-address=:9100

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/node_exporter.service"

    - name: Reload systemd configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start NodeExporter service
      ansible.builtin.systemd:
        name: node_exporter
        enabled: yes
        state: started

    - name: Check NodeExporter status
      ansible.builtin.systemd:
        name: node_exporter
        state: status

        
