---
- name: Setup Kernel Modules and Settings
  hosts: worker
  become: true

  tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes
               
    - name: Install iptables-persistent package
      apt:
        name: iptables-persistent
        state: present
              
    - name: Disable Swap
      command: swapoff -a

    - name: Persist Swap Changes
      replace:
        path: /etc/fstab       
        regexp: '^/swap.img\s'
        replace: '#/swap.img      none    swap    sw      0       0'
       
    - name: Install curl apt-transport-https git iptables-persistent
      apt:
        name:
          - curl
          - apt-transport-https
          - git
          - iptables-persistent
        state: present

    - name: Load br_netfilter Module
      command: modprobe br_netfilter
      become: true
      become_method: sudo
      become_user: root
      tags:
        - kernel

    - name: Load overlay Module
      command: modprobe overlay
      become: true
      become_method: sudo
      become_user: root
      tags:
        - kernel

    - name: Load Additional Kernel Modules
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        state: present
        sysctl_set: yes
      become: true
      become_method: sudo
      become_user: root
      tags:
        - kernel

    - name: Apply System Settings
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        sysctl_set: yes
      with_items:
        - net.ipv4.ip_forward
        - net.ipv4.conf.all.rp_filter
        - net.ipv4.conf.default.rp_filter
        - net.bridge.bridge-nf-call-arptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
      become: true
      become_method: sudo
      become_user: root
      tags:
        - kernel
      run_once: true

    - name: Reload System Settings
      command: sysctl --system
      become: true
      become_method: sudo
      become_user: root
      tags:
        - kernel

    - name: Add Kubernetes apt repository key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg 
    
    - name: Add Kubernetes apt repository
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
    
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install docker dockerd.io kubelet kubeadm kubectl iptables-persistent
      apt:
        name:
          - docker
          - docker.io
          - kubelet 
          - kubeadm 
          - kubectl          
          - iptables-persistent
        state: present
                
    - name: Hold kubelet, kubeadm, and kubectl packages
      command: apt-mark hold kubelet kubeadm kubectl

    - name: copy daemon.json
      copy:
        src: /home/ansible/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root

    - name: kubectl_version
      command: kubectl version --client --output=yaml
      register: kubectl_version

    - name: Display status
      debug:
        var: kubectl_version.stdout_lines

    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Enable and start docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted
        enabled: true
