---

- name: Install and configure NTP on servers
  hosts: nodes
  become: true

  tasks:
    - name: Install NTP package
      apt:
        name: ntpdate
        state: present

    # - name: Install EPEL repo.
    #   yum: name=epel-release state=present

    # - name: Install htop package
    #   yum:
    #     name: htop
    #     state: present

    - name: Configure NTP server
      command: ntpdate pool.ntp.org
      ignore_errors: yes

    - name: copy  resolv.conf
      copy:
        src: k8s-test/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root

    - name: Restart NTP service
      service:
        name: ntpd
        state: restarted

    - name: Verify NTP synchronization
      command: ntpq -p
      register: ntp_status

    - name: Display NTP synchronization status
      debug:
        var: ntp_status.stdout_lines
