name: Ansible Playbook Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: playbooks/setup-node@v1
      with:
          node-version: 15

    - name: Run Ansible playbook
      uses: AlexandrYurlov-1989/playbooks@main
      with:
        playbook: ping.yaml # path to your Ansible playbook
        directory: ./
        key: ${{ secrets.SSH_PRIVATE_KEY }} # the ssh private key for ansible to use to connect to the servers, stored as "ansible_ssh_private_key" in the GitHub secrets
        inventory: ${{ secrets.ansible_inventory }} # the ansible inventory to use, stored as "ansible_inventory" in the GitHub secrets
    
