name: my-git-basics

on:
  push:
    branches: 
      - master
        
jobs: 
  my-test:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello worold"

  my-test-2:   
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Уже можно попробовать команду"
    


